server:
  servlet:
    context-path: /api
  port: 8084

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5436/postgres
    password: postgres
    username: postgres

microservices:
  user:
    url: http://localhost:8082/api
  cart:
    url: http://localhost:8083/api
  product:
    url: http://localhost:8081/api
